/**
 * Seed database from wiki sources (references/*.wiki) and app data.
 * Requires: npm install mysql2 dotenv
 * Copy .env.example to .env and set DB_HOST, DB_USER, DB_PASSWORD, DB_NAME.
 * Run: node database/seed.js
 */

import mysql from 'mysql2/promise'
import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { config as loadEnv } from 'dotenv'

const __dirname = dirname(fileURLToPath(import.meta.url))
loadEnv({ path: join(__dirname, '..', '.env') })

const config = {
  host: process.env.DB_HOST || '192.232.249.125',
  user: process.env.DB_USER || 'redsaber_antisemitism',
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME || 'redsaber_antisemitism',
}

if (!config.password) {
  console.error('Set DB_PASSWORD in .env (e.g. copy .env.example to .env)')
  process.exit(1)
}

// Timeline events: sources = cited URLs/publications from the .wiki reference files (not the wiki files themselves)
const TIMELINE_EVENTS = [
  { year: -2000, label: 'Origins of Judaism', region: 'levant', description: 'Judaism dates back to around 2000 B.C.; first Abrahamic faith, tracing to Abraham.', source_label: 'Judaism 101', source_url: 'http://www.jewfaq.org/index.htm' },
  { year: -1446, label: 'Exodus from Egypt', region: 'levant', description: 'Moses leads the Hebrews from Egypt; Ten Commandments at Mount Sinai.', source_label: 'Internet Jewish History Sourcebook', source_url: 'http://www.fordham.edu/halsall/jewish/jewishsbook.html' },
  { year: -1050, label: 'Saul, first king of Israel', region: 'levant', description: 'First monarchy under King Saul; Hebrews unite under a king after the period of the Judges.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: -1010, label: 'Kingdom under David', region: 'levant', description: 'David expands the kingdom (c. 1010–970 B.C.); Jerusalem becomes capital.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: -1000, label: 'Kingdom of Israel', region: 'levant', description: 'United monarchy under David and Solomon.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: -930, label: 'Split: Judah and Israel', region: 'levant', description: 'After Solomon, the kingdom splits: Judah (south) and Israel (north) with capital at Samaria.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: -722, label: 'Fall of Northern Kingdom', region: 'levant', description: 'Assyrians conquer northern Kingdom of Israel (721/722 B.C.); exile of northern tribes; "Lost Ten Tribes."', source_label: 'Jewfaq – What Is Judaism?', source_url: 'http://www.jewfaq.org/judaism.htm' },
  { year: -586, label: 'Babylonian conquest of Judah', region: 'levant', description: 'Southern Kingdom conquered by Babylonians; population exiled to Babylon (586/7 B.C.).', source_label: 'Jewfaq – What Is Judaism?', source_url: 'http://www.jewfaq.org/judaism.htm' },
  { year: -538, label: 'Cyrus allows return', region: 'levant', description: 'Cyrus of Persia allows Jews to return to ancestral homeland; Babylonian Talmud develops.', source_label: 'Jewfaq – What Is Judaism?', source_url: 'http://www.jewfaq.org/judaism.htm' },
  { year: -516, label: 'Second Temple built', region: 'levant', description: 'Second Temple completed (520–516 B.C.) under Persian rule.', source_label: 'An Encyclopedia of World History (Kingsport Press, 1948)', source_url: null },
  { year: -445, label: 'Nehemiah rebuilds Jerusalem', region: 'levant', description: 'Nehemiah rebuilds the walls of Jerusalem under Persian approval; opposition from other peoples in the land.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: -332, label: 'Alexander the Great', region: 'levant', description: 'Alexander sweeps through Israel; Persian rule replaced by Greek (Hellenism).', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: -198, label: 'Seleucids take Israel', region: 'levant', description: 'Seleucid (Syrian) Greeks push back Ptolemies and take control of Judah and Galilee.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: -168, label: 'Maccabean revolt', region: 'levant', description: 'Judaism declared illegal; Temple desecrated; revolt under Maccabees; Hanukkah.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: -142, label: 'Hasmonean independence', region: 'levant', description: 'Full independence from Seleucids (with Roman pressure); Jewish kingdom restored until Roman takeover.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: -63, label: 'Roman rule', region: 'levant', description: 'Pompey and Rome take control; Israel under Roman rule as province of Palestine.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 66, label: 'First Jewish–Roman War', region: 'levant', description: 'First major revolt against Rome; leads to siege of Jerusalem and eventual destruction of the Temple.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 70, label: 'Destruction of Second Temple', region: 'levant', description: 'Romans destroy the Temple in Jerusalem; Jews dispersed to Rome, Rhine (Ashkenaz), and beyond.', source_label: 'Jewfaq – What Is Judaism?', source_url: 'http://www.jewfaq.org/judaism.htm' },
  { year: 90, label: 'Council of Jamnia', region: 'levant', description: 'Jewish canon of Scripture defined at Yavneh; Hebrew Scriptures elevated; basis for later Masoretic tradition.', source_label: 'Jewfaq – What Is Judaism?', source_url: 'http://www.jewfaq.org/judaism.htm' },
  { year: 135, label: 'Bar Kokhba revolt', region: 'levant', description: 'Third revolt against Rome fails; Romans force Jews to leave; diaspora widens.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 200, label: 'Mishna period', region: 'levant', description: 'Mishna developed (200 B.C.–200 A.D.); Talmudic literature begins; Halakha and Aggadah.', source_label: 'Jewfaq – What Is Judaism?', source_url: 'http://www.jewfaq.org/judaism.htm' },
  { year: 500, label: 'Gemara / Talmud', region: 'levant', description: 'Gemara (200–500 A.D.) with Mishna comprises Talmud; regulates Jewish life until modern times.', source_label: 'Jewfaq – What Is Judaism?', source_url: 'http://www.jewfaq.org/judaism.htm' },
  { year: 635, label: 'Muslim conquest of Israel', region: 'levant', description: 'Muslim armies conquer the land; Jews become dhimmis (second-class citizens) in their own land.', source_label: 'Emmanuel Navon, The Star and the Scepter (JPS, 2020)', source_url: 'https://books.google.com/books?id=kOT8DwAAQBAJ&pg=PA54' },
  { year: 1009, label: 'Leningrad Codex', region: 'europe', description: 'Oldest complete copy of the Hebrew Bible (Masoretic Text); manuscript from 1009 A.D.', source_label: 'Judaism 101', source_url: 'http://www.jewfaq.org/index.htm' },
  { year: 1096, label: 'First Crusade', region: 'europe', description: 'Pogroms against Jewish communities in Europe and in the Holy Land.', source_label: 'Internet Jewish History Sourcebook', source_url: 'http://www.fordham.edu/halsall/jewish/jewishsbook.html' },
  { year: 1290, label: 'End of Crusader states', region: 'levant', description: 'Last Crusader state in the Holy Land falls; region under Mameluke then later Ottoman control.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1492, label: 'Expulsion from Spain', region: 'europe', description: 'Alhambra Decree; Jews expelled from Spain (Golden Age ended); Sephardim disperse to Mediterranean and Americas.', source_label: 'Jewfaq – What Is Judaism?', source_url: 'http://www.jewfaq.org/judaism.htm' },
  { year: 1517, label: 'Ottoman rule', region: 'levant', description: 'Ottoman Turks control region (1517–1917); Mizrahi designation for non-European Jews.', source_label: 'Jewfaq – What Is Judaism?', source_url: 'http://www.jewfaq.org/judaism.htm' },
  { year: 1834, label: 'Safed pogrom', region: 'levant', description: 'Arabs of Galilee attack Jews of Safed; 33 days of rape, looting, and murder; Jewish property destroyed.', source_label: 'Hanan Amior, Presspectiva (2015)', source_url: 'https://presspectiva.org.il/%D7%91%D7%94%D7%90%D7%A8%D7%A5-%D7%A0%D7%98%D7%A2%D7%9F-%D7%A9%D7%94%D7%9B%D7%99%D7%91%D7%95%D7%A9-%D7%94%D7%95%D7%90-%D7%91%D7%99%D7%AA-%D7%94%D7%99%D7%95%D7%A6%D7%A8-%D7%A9%D7%9C-%D7%94%D7%98/' },
  { year: 1894, label: 'Dreyfus affair', region: 'europe', description: 'French Jewish officer Alfred Dreyfus wrongly convicted; socialist press denounced philo-Semitic defense; galvanized Zionism.', source_label: 'Joseph Telushkin, Jewish Literacy (HarperCollins, 2008)', source_url: 'https://books.google.com/books?id=bIHtJzYCkqEC' },
  { year: 1897, label: 'First Zionist Congress', region: 'europe', description: 'Basel; founding of modern political Zionism under Herzl.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1917, label: 'Balfour Declaration', region: 'europe', description: 'British government support for a Jewish homeland in Palestine.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1920, label: 'British Mandate', region: 'levant', description: 'Palestine under British mandate; Jewish immigration increases.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1921, label: 'Jaffa riots', region: 'levant', description: 'Arab riots begin in Jaffa and spread; dozens of Jews murdered (46 years before 1967).', source_label: 'CET – 1921 riots', source_url: 'http://lib.cet.ac.il/pages/item.asp?item=2039' },
  { year: 1929, label: 'Hebron massacre', region: 'levant', description: 'Arab riots; massacre of Jewish community in Hebron and Safed; hundreds killed and wounded.', source_label: 'Hanan Amior, Presspectiva (2015)', source_url: 'https://presspectiva.org.il/%D7%91%D7%94%D7%90%D7%A8%D7%A5-%D7%A0%D7%98%D7%A2%D7%9F-%D7%A9%D7%94%D7%9B%D7%99%D7%91%D7%95%D7%A9-%D7%94%D7%95%D7%90-%D7%91%D7%99%D7%AA-%D7%94%D7%99%D7%95%D7%A6%D7%A8-%D7%A9%D7%9C-%D7%94%D7%98/' },
  { year: 1936, label: 'Arab revolt', region: 'levant', description: 'Arab revolt 1936–39; British restrict Jewish immigration (White Paper 1939).', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1939, label: 'White Paper of 1939', region: 'levant', description: 'British limit Jewish immigration to Palestine at a time of dire need for Jews fleeing Europe.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1947, label: 'UN partition plan', region: 'levant', description: 'UN proposes partition of Palestine into Jewish and Arab states; Arab states reject; violence escalates.', source_label: "Jeffrey Herf, Israel's Moment (Cambridge, 2022)", source_url: 'https://books.google.com/books?id=8YlZEAAAQBAJ&pg=PA235' },
  { year: 1948, label: 'State of Israel', region: 'levant', description: 'Declaration of independence May 14, 1948; immediately invaded by neighboring Arab states.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1967, label: 'Six-Day War', region: 'levant', description: 'Israel gains Sinai, Gaza, West Bank, Golan, East Jerusalem; East German Communists use former Nazi propagandists for anti-Israel propaganda.', source_label: 'Jeffrey Herf, Divided Memory (Harvard, 1997)', source_url: 'https://books.google.com/books?id=yahqnBEEbQEC' },
  { year: 1973, label: 'Yom Kippur War', region: 'levant', description: 'Egypt and Syria attack on Yom Kippur; Israel pushes back with U.S./Soviet diplomacy.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1976, label: 'Entebbe raid', region: 'europe', description: 'PFLP and German leftists hijack Air France flight; Jewish passengers singled out for murder; Israeli rescue at Entebbe.', source_label: 'Stephen E. Atkins, Encyclopedia of modern worldwide extremists (Greenwood, 2004)', source_url: 'https://books.google.com/books?id=b8k4rEPvq_8C' },
  { year: 1979, label: 'Israel–Egypt peace', region: 'levant', description: 'Camp David; peace treaty between Israel and Egypt.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1979, label: 'Sandinistas target Jews', region: 'americas', description: 'Marxist Sandinistas seize Nicaragua; synagogue bombed and confiscated; many of ~250 Jews flee.', source_label: 'U.S. State Dept., International Religious Freedom Report – Nicaragua (2001)', source_url: 'http://www.state.gov/g/drl/rls/irf/2001/5681.htm' },
  { year: 1985, label: 'Achille Lauro / Klinghoffer', region: 'europe', description: 'PLF (Communist) hijacks cruise ship; Leon Klinghoffer murdered and dumped overboard because he was Jewish.', source_label: 'Sun-Sentinel / ADL – Achille Lauro', source_url: 'https://articles.sun-sentinel.com/2003-04-17/news/0304161228_1_achille-lauro-abul-abbas-palestinian-authority' },
  { year: 1991, label: 'Madrid Conference', region: 'europe', description: 'Landmark conference; Israel, Palestinians, and Arab states in direct talks; basis for later Oslo.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1993, label: 'Oslo Accords', region: 'levant', description: 'Israel and PLO sign Declaration of Principles.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 1995, label: 'Rabin assassinated', region: 'levant', description: 'Prime Minister Yitzhak Rabin assassinated by right-wing Jewish radical; Peres continues peace efforts.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 2017, label: 'US recognizes Jerusalem', region: 'levant', description: 'U.S. recognizes Jerusalem as capital of Israel and moves embassy from Tel Aviv.', source_label: 'Jewish Virtual Library', source_url: 'http://www.jewishvirtuallibrary.org/' },
  { year: 2020, label: 'Abraham Accords', region: 'levant', description: 'UAE, Bahrain normalize relations with Israel; later Kosovo, Serbia.', source_label: 'UPI / USA Today (Sept 2020)', source_url: 'https://www.upi.com/Top_News/US/2020/09/15/UAE-Bahrain-Israel-normalize-relations-in-White-House-ceremony/1331600180371/' },
  { year: 2023, label: 'Oct 7 attacks', region: 'levant', description: 'Hamas attack on Israel; war in Gaza.', source_label: null, source_url: null },
]

// Hashem.Faith further-reading links (https://hashem.faith/post-sitemap.xml) — stored in DB and used for definitions/misconceptions
const HASHEM = 'https://hashem.faith'
const DEFINITION_FURTHER_READING = {
  jew: [
    { label: 'Is Judaism a religion or race?', url: `${HASHEM}/is-judaism-a-religion-or-race/` },
    { label: 'Is Jewish a language?', url: `${HASHEM}/is-jewish-a-language/` },
  ],
  talmud: [
    { label: 'What is the Talmud?', url: `${HASHEM}/what-is-the-talmud/` },
    { label: 'Is the Talmud more holy than the Bible?', url: `${HASHEM}/is-the-talmud-more-holy-than-the-bible/` },
    { label: 'Are Jews commanded to lie about the Talmud?', url: `${HASHEM}/are-jews-commanded-to-lie-about-the-talmud/` },
    { label: 'Christianity in the Talmud', url: `${HASHEM}/christianity-in-the-talmud/` },
    { label: 'Gentiles are human', url: `${HASHEM}/gentiles-are-human/` },
    { label: 'Gentiles are not animals', url: `${HASHEM}/gentiles-are-not-animals/` },
    { label: 'The Jesus narrative in the Talmud', url: `${HASHEM}/the-jesus-narrative-in-the-talmud/` },
    { label: 'Jesus in the Talmud', url: `${HASHEM}/jesus-in-the-talmud/` },
  ],
  genocide: [],
  antisemitism: [
    { label: 'Should AIPAC be registered under FARA?', url: `${HASHEM}/should-aipac-be-registered-under-fara/` },
    { label: 'Does AIPAC fall under 22 USC 611?', url: `${HASHEM}/does-aipac-fall-under-22-usc-611/` },
  ],
  zionism: [
    { label: 'What does Israel mean?', url: `${HASHEM}/what-does-israel-mean/` },
  ],
  agitprop: [],
  goy: [
    { label: 'Where do gentiles fit into the Jewish world view?', url: `${HASHEM}/where-do-gentiles-fit-into-the-jewish-world-view/` },
    { label: 'Gentiles are human', url: `${HASHEM}/gentiles-are-human/` },
    { label: 'Gentiles are not animals', url: `${HASHEM}/gentiles-are-not-animals/` },
  ],
  israel: [{ label: 'What does Israel mean?', url: `${HASHEM}/what-does-israel-mean/` }],
  zog: [],
  holocaust: [],
  'axis-of-evil': [],
  fara: [
    { label: 'Should AIPAC be registered under FARA?', url: `${HASHEM}/should-aipac-be-registered-under-fara/` },
    { label: 'Does AIPAC fall under 22 USC 611?', url: `${HASHEM}/does-aipac-fall-under-22-usc-611/` },
  ],
  torah: [{ label: 'What is the Talmud?', url: `${HASHEM}/what-is-the-talmud/` }],
  tanakh: [],
}
const MISCONCEPTION_FURTHER_READING = {
  israel: [{ label: 'What does Israel mean?', url: `${HASHEM}/what-does-israel-mean/` }],
  talmud: [
    { label: 'What is the Talmud?', url: `${HASHEM}/what-is-the-talmud/` },
    { label: 'Are Jews commanded to lie about the Talmud?', url: `${HASHEM}/are-jews-commanded-to-lie-about-the-talmud/` },
    { label: 'Gentiles are human', url: `${HASHEM}/gentiles-are-human/` },
    { label: 'Gentiles are not animals', url: `${HASHEM}/gentiles-are-not-animals/` },
    { label: 'Christianity in the Talmud', url: `${HASHEM}/christianity-in-the-talmud/` },
  ],
  'jewish-race': [
    { label: 'Is Judaism a religion or race?', url: `${HASHEM}/is-judaism-a-religion-or-race/` },
    { label: 'Where do gentiles fit into the Jewish world view?', url: `${HASHEM}/where-do-gentiles-fit-into-the-jewish-world-view/` },
    { label: 'Gentiles are human', url: `${HASHEM}/gentiles-are-human/` },
    { label: 'Gentiles are not animals', url: `${HASHEM}/gentiles-are-not-animals/` },
  ],
  conspiracy: [
    { label: 'Did the Jews kill Jesus?', url: `${HASHEM}/did-the-jews-kill-jesus/` },
    { label: 'Should AIPAC be registered under FARA?', url: `${HASHEM}/should-aipac-be-registered-under-fara/` },
  ],
}

// Definitions (from app); body_text enriched with context that Hashem.Faith articles address
const DEFINITIONS = [
  { slug: 'jew', title: 'Jew', summary: 'Who is a Jew? Religion, people, and identity.', body_text: 'A Jew is someone who belongs to the Jewish people—either by religion (Judaism), ancestry, or both. Judaism is both an ethnoreligion and a tradition. Many Jews identify as a people or nation (am Yisrael) as well as a religion. Conversion to Judaism is possible; converts are fully Jewish. Jewish identity has been passed down for millennia through family and community, often in the face of persecution. Questions like whether Judaism is a religion or a race, or whether "Jewish" refers to a language (Hebrew or Yiddish), are addressed in depth at Hashem.Faith with sourced explanations.' },
  { slug: 'goy', title: 'Goy', summary: 'Hebrew/Yiddish term for a non-Jew; meaning and misuse.', body_text: 'Goy (Hebrew גוי, plural goyim) is the Hebrew and Yiddish word for a non-Jew—equivalent to "gentile" in English. It literally means "nation" or "people" and in Jewish usage is neutral, not derogatory. Antisemites sometimes claim that Jews use the word to demean non-Jews. In Jewish texts and everyday speech, goy is simply the term for someone who is not Jewish. Hashem.Faith has articles on how gentiles are viewed in Jewish tradition.' },
  { slug: 'talmud', title: 'Talmud', summary: 'What is the Talmud? Central text of Rabbinic Judaism.', body_text: 'The Talmud is the central text of Rabbinic Judaism—comprising the Mishnah (oral law, redacted around 200 CE) and the Gemara (commentaries and discussions). It is not a single book but a vast body of law, narrative, and debate. It is often misquoted or taken out of context by antisemites. Understanding it requires study and context; isolated quotes are easily weaponized. Common antisemitic myths—that the Talmud is "more holy" than the Bible, that Jews are commanded to lie about it, that it dehumanizes gentiles or attacks Christianity—are refuted with primary-source context in articles at Hashem.Faith.' },
  { slug: 'torah', title: 'Torah', summary: 'The first five books of the Hebrew Bible and Jewish teaching.', body_text: 'The Torah is the first five books of the Hebrew Bible: Genesis, Exodus, Leviticus, Numbers, and Deuteronomy. It is the foundational scripture of Judaism. In broader Jewish usage, "Torah" can mean the entire body of Jewish teaching and law, including the Talmud. The Torah is read in synagogue and studied as the core of Jewish life.' },
  { slug: 'tanakh', title: 'Tanakh', summary: 'The Hebrew Bible: Torah, Prophets, and Writings.', body_text: 'The Tanakh is the Hebrew Bible—the canonical scripture of Judaism. The name is an acronym: Torah (Teaching), Nevi\'im (Prophets), and Ketuvim (Writings). It corresponds to what Christianity calls the Old Testament. The Tanakh is the written foundation of Jewish belief and practice.' },
  { slug: 'israel', title: 'Israel', summary: 'The state, the people, and the name.', body_text: 'Israel can mean: (1) the modern State of Israel, established in 1948; (2) the ancient kingdoms of Israel and Judah; (3) the biblical name for the Jewish people (literally "one who wrestles with God," from the story of Jacob). Jewish ties to the land are ancient and continuous. Hashem.Faith explores what "Israel" means biblically and historically.' },
  { slug: 'genocide', title: 'Genocide', summary: 'Legal and historical definition—and when it applies.', body_text: 'Under international law (UN Genocide Convention, 1948), genocide means acts committed with intent to destroy, in whole or in part, a national, ethnical, racial or religious group. The key is intent to destroy the group as such. The Holocaust and Inquisition are clear cases; the Gaza war is not.' },
  { slug: 'holocaust', title: 'Holocaust', summary: 'The Nazi genocide of European Jewry (1933–1945).', body_text: 'The Holocaust (Hebrew Shoah) was the systematic genocide of European Jewry by Nazi Germany and its collaborators, roughly 1933–1945. Approximately six million Jews were murdered—two-thirds of European Jewry. Holocaust denial or minimization is antisemitic. The evidence—documentation, testimony, sites, and scholarship—is overwhelming.' },
  { slug: 'antisemitism', title: 'Antisemitism', summary: 'Hatred or prejudice against Jews.', body_text: 'Antisemitism is prejudice, hatred, or discrimination against Jews as Jews. The term was coined in the 19th century but the phenomenon is ancient. It includes stereotypes, conspiracy theories, denial of Jewish rights (including to a state), and violence. The IHRA working definition is widely used for identifying antisemitism in policy and education. Claims that groups like AIPAC should register as "foreign agents" (FARA) often overlap with conspiracy tropes; Hashem.Faith examines the legal and factual basis for such claims.' },
  { slug: 'zionism', title: 'Zionism', summary: 'Jewish self-determination and the state of Israel.', body_text: 'Zionism is the movement for Jewish self-determination and a national home in the ancestral homeland, Israel. Modern political Zionism emerged in the late 19th century in response to antisemitism and the desire for a sovereign Jewish state. Support for Israel\'s right to exist is not "colonialism"; Jewish ties to the land are ancient and continuous. The meaning of the name "Israel" and its biblical and historical significance are explored at Hashem.Faith.' },
  { slug: 'zog', title: 'ZOG', summary: '"Zionist Occupied Government"—antisemitic conspiracy term.', body_text: 'ZOG stands for "Zionist Occupied Government." It is a conspiracy term used by white supremacists and antisemites to claim that Jews secretly control the U.S. government—and by extension, media, finance, and culture. There is no evidence for this. The idea recycles centuries-old antisemitic conspiracy myths.' },
  { slug: 'axis-of-evil', title: 'Axis of Evil', summary: 'U.S. phrase for state sponsors of terrorism; sometimes misused.', body_text: '"Axis of Evil" was a phrase used by U.S. President George W. Bush in 2002 to describe governments that sponsor terrorism: Iraq, Iran, and North Korea. The term is sometimes misused in antisemitic or anti-Israel rhetoric to suggest that Israel or "Zionists" are part of a global evil conspiracy.' },
  { slug: 'fara', title: 'FARA', summary: 'Foreign Agents Registration Act and how it is weaponized against Jews.', body_text: 'FARA is the U.S. Foreign Agents Registration Act. It requires people and groups acting as agents of foreign principals to register and disclose their activities. Antisemitic rhetoric often demands that pro-Israel advocacy groups (e.g. AIPAC) register under FARA, implying they are "foreign agents." Hashem.Faith examines whether such groups fall under the law.' },
  { slug: 'agitprop', title: 'Agitprop', summary: 'Agitation and propaganda—how political messaging is used to sway opinion.', body_text: 'Agitprop (from "agitation" + "propaganda") is political messaging designed to agitate and mobilize people rather than to inform. It uses slogans, imagery, and one-sided framing to provoke strong emotion and action. Antisemitic and anti-Israel narratives are often spread through agitprop: memes, chants, and distorted claims that bypass critical thinking. Recognizing agitprop helps you separate emotional manipulation from factual argument.' },
]

// Agitators (from app). image_url = Wikimedia Commons (CC/PD) direct link via Special:FilePath.
const AGITATORS = [
  { slug: 'tucker-carlson', name: 'Tucker Carlson', subtitle: 'Mainstreaming antisemitic tropes and white-nationalist talking points', description: 'Former Fox News host who has repeatedly platformed antisemitic guests, promoted replacement theory, and used dog whistles about "globalists" and "cosmopolitan elites" that antisemites interpret as Jews.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tucker_Carlson_2020_%28cropped%29.jpg', sources: [
    { date_label: '2022', text: 'Platformed white nationalist Nick Fuentes and Ye (Kanye West) after antisemitic outbursts.', url: null },
    { date_label: '2023', text: 'Suggested Jewish influence over media and "why do I have to love the Holocaust?" rhetoric.', url: null },
    { date_label: '2024', text: 'Continued rhetoric about "globalist" elites and opposition to Israel aid.', url: null },
  ]},
  { slug: 'thomas-massie', name: 'Thomas Massie', subtitle: 'Voting against Holocaust remembrance and Israel support', description: 'U.S. Representative who has voted against Holocaust education funding and aid to Israel, and made statements that critics say downplay antisemitism or align with isolationist, anti-Israel narratives.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Thomas_Massie_1.jpg', sources: [
    { date_label: '2024', text: 'Voted against Holocaust Education Act and Israel aid package.', url: null },
    { date_label: 'Various', text: 'Consistent "America First" votes against foreign aid including to Israel.', url: null },
  ]},
  { slug: 'david-duke', name: 'David Duke', subtitle: 'Former KKK leader and open white supremacist', description: 'Former Ku Klux Klan leader and white nationalist who has run for office repeatedly. Openly antisemitic, promoting conspiracy theories about Jewish control and Holocaust minimization.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/David_Duke.jpg', sources: [
    { date_label: 'Decades', text: 'Public speeches and writings blaming Jews for societal ills and promoting white supremacy.', url: null },
  ]},
  { slug: 'nick-fuentes', name: 'Nick Fuentes', subtitle: 'White nationalist streamer and Holocaust denier', description: 'Far-right streamer and activist who promotes white nationalism, Holocaust denial, and open antisemitism. Has been deplatformed from major services; continues to reach audiences via alternative platforms.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nick_Fuentes_screencap_from_July_2022_virtual_debate_%283x4_cropped%29.png', sources: [
    { date_label: '2022', text: 'Dinner with Ye and Donald Trump; Fuentes has repeatedly denied the Holocaust.', url: null },
    { date_label: 'Ongoing', text: 'Streams and rallies promoting antisemitic and white nationalist ideology.', url: null },
  ]},
  { slug: 'ilhan-omar', name: 'Ilhan Omar', subtitle: 'Tropes about Jewish money and dual loyalty', description: 'U.S. Representative who has been criticized for statements invoking antisemitic tropes—e.g., that U.S. support for Israel is "all about the Benjamins," and suggestions of dual loyalty—which draw on classic antisemitic canards.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ilhan_Omar%2C_official_portrait%2C_116th_Congress_%28cropped%29_A.jpg', sources: [
    { date_label: '2019', text: '"It\'s all about the Benjamins" tweet about AIPAC; dual loyalty tropes.', url: null },
    { date_label: 'Later', text: 'Additional statements on Israel and lobbying that critics say repeat tropes.', url: null },
  ]},
  { slug: 'candace-owens', name: 'Candace Owens', subtitle: 'Downplaying antisemitism and defending antisemitic figures', description: 'Commentator and host who has repeatedly downplayed antisemitism and defended figures who made antisemitic statements. She has suggested that discussion of the Holocaust is overemphasized and defended Kanye West after his antisemitic outbursts, framing criticism as political rather than a response to hate speech.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Candace_Owens_by_Gage_Skidmore_%28cropped%29.jpg', sources: [
    { date_label: '2022', text: 'Defended Ye (Kanye West) after antisemitic comments; suggested the issue was being weaponized.', url: null },
    { date_label: '2023', text: 'Remarks that critics say minimize the significance of Holocaust education and antisemitism.', url: null },
  ]},
  { slug: 'marjorie-taylor-greene', name: 'Marjorie Taylor Greene', subtitle: 'Jewish space lasers, Soros tropes, and Holocaust comparisons', description: 'U.S. Representative who has promoted antisemitic conspiracy imagery and tropes. She suggested that a Jewish family (Rothschilds) and space-based lasers were behind wildfires; has invoked George Soros in conspiratorial ways; and compared COVID safety measures to the Holocaust, trivializing the genocide of Jews.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Marjorie_Taylor_Greene_117th_Congress_portrait.jpeg', sources: [
    { date_label: '2018', text: 'Facebook post linking Rothschild Inc. and space lasers to wildfires; later deleted.', url: null },
    { date_label: '2021–present', text: 'Holocaust comparisons (masks, vaccines) and Soros tropes.', url: null },
  ]},
  { slug: 'greta-thunberg', name: 'Greta Thunberg', subtitle: 'Antisemitic imagery and tropes in Israel–Gaza activism', description: 'Climate activist who has been criticized for sharing and endorsing content that used antisemitic imagery and tropes in the context of Israel and Gaza. She posted an image of an octopus as a symbol of "colonization" that echoed classic antisemitic "Jewish control" imagery, and has repeated one-sided "genocide" framing that conflates Jews and the State of Israel.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Greta_Thunberg_2024_03.jpg', sources: [
    { date_label: '2023', text: 'Shared octopus image with antisemitic connotations; later removed after criticism.', url: null },
    { date_label: '2024', text: 'Continued rhetoric that critics say demonizes Israel and blurs Jews with Israeli policy.', url: null },
  ]},
  { slug: 'cenk-uygur', name: 'Cenk Uygur', subtitle: '"Jewish lobby" and dual-loyalty tropes', description: 'Founder and host of The Young Turks who has been criticized for rhetoric that invokes antisemitic tropes about Jewish or "Israel lobby" control of U.S. policy and media. Critics point to language that suggests dual loyalty and secret influence, which echoes classic antisemitic canards.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cenk_Uygur_hosting_The_Young_Turks_%2826942059034%29.jpg', sources: [
    { date_label: 'Various', text: 'Statements about "Jewish lobby," AIPAC, and U.S. policy that critics say use dual-loyalty tropes.', url: null },
  ]},
  { slug: 'ana-kasparian', name: 'Ana Kasparian', subtitle: 'Tropes about Jewish influence and lobbying', description: 'Host and commentator at The Young Turks who has made statements about Israel and pro-Israel advocacy that critics say rely on antisemitic tropes—including suggestions of undue Jewish or "lobby" influence over politics and media, and framing that echoes dual-loyalty and control narratives.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ana_Kasparian_%2827871435561%29_%28cropped%29.jpg', sources: [
    { date_label: 'Various', text: 'Comments on Israel, AIPAC, and "lobby" influence that critics say invoke antisemitic tropes.', url: null },
  ]},
  { slug: 'ms-rachel', name: 'Ms. Rachel', subtitle: 'Controversy over Gaza letter and perceived one-sidedness', description: 'Children\'s educator and internet personality who faced criticism for signing an open letter related to Israel and Gaza that some Jewish and pro-Israel groups said was one-sided, downplayed Hamas terrorism, or contributed to an environment where antisemitic rhetoric flourishes. The controversy centers on the framing of the conflict and the impact of such statements on Jewish families and educators.', image_url: '/agitators/msrachel.webp', sources: [
    { date_label: '2023–2024', text: 'Signed open letter on Gaza that drew criticism from Jewish organizations and parents.', url: null },
  ]},
  { slug: 'stew-peters', name: 'Stew Peters', subtitle: 'Antisemitic conspiracy theories and Great Replacement', description: 'Far-right host and podcaster who has promoted antisemitic conspiracy theories, including Great Replacement rhetoric and tropes about "globalists" and elite control that antisemites interpret as Jews. His show has platformed guests who spread Holocaust denial and other antisemitic content.', image_url: '/agitators/stewpeters.jpg', sources: [
    { date_label: 'Ongoing', text: 'Show content and guests promoting replacement theory and antisemitic conspiracy tropes.', url: null },
  ]},
  { slug: 'dan-bilzerian', name: 'Dan Bilzerian', subtitle: 'Antisemitic posts and memes on social media', description: 'Social media personality and poker player who has posted antisemitic memes and comments online. His posts have included classic antisemitic imagery and conspiracy tropes, contributing to normalization of Jew-hatred in online spaces.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dan_Bilzerian.jpg', sources: [
    { date_label: 'Various', text: 'Social media posts containing antisemitic imagery and conspiracy rhetoric.', url: null },
  ]},
  { slug: 'lucas-gage', name: 'Lucas Gage', subtitle: 'Antisemitic rhetoric and Holocaust minimization', description: 'Streamer and online commentator who has promoted antisemitic rhetoric and Holocaust minimization. He has used "globalist" and "Zionist" conspiracy language and made statements that downplay or distort the Holocaust and Jewish experience.', image_url: '/agitators/lucasgage.jpg', sources: [
    { date_label: 'Ongoing', text: 'Streams and posts featuring antisemitic tropes and Holocaust minimization.', url: null },
  ]},
  { slug: 'jackson-hinkle', name: 'Jackson Hinkle', subtitle: 'Anti-Israel rhetoric that crosses into antisemitic tropes', description: 'Social media commentator known for virulent anti-Israel content who has repeatedly used rhetoric that critics say crosses into antisemitic tropes: conspiracy framing about "Zionist" control of media and government, and content that blurs Jews with the Israeli state and dehumanizes Israelis.', image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jackson_Hinkle_2022.png', sources: [
    { date_label: '2023–2024', text: 'Posts and commentary invoking "Zionist" control and conspiracy tropes; millions of followers.', url: null },
  ]},
  { slug: 'jake-shields', name: 'Jake Shields', subtitle: 'Antisemitic conspiracy posts and "globalist" rhetoric', description: 'MMA fighter and social media figure who has posted antisemitic conspiracy content online, including references to George Soros and "globalists" in ways that echo classic antisemitic tropes about Jewish power and control.', image_url: '/agitators/jakeshields.jpg', sources: [
    { date_label: 'Various', text: 'Social media posts promoting antisemitic conspiracy theories and "globalist" tropes.', url: null },
  ]},
  { slug: 'ian-carroll', name: 'Ian Carroll', subtitle: 'Antisemitic and extreme anti-Israel conspiracy content', description: 'Commentator and podcaster who has promoted or platformed antisemitic and extreme anti-Israel conspiracy content. His rhetoric and guests have included tropes about "Zionist" or Jewish control and narratives that demonize Israel and blur distinctions between Jews and Israeli policy.', image_url: '/agitators/iancarroll.jpg', sources: [
    { date_label: 'Ongoing', text: 'Content and guests that critics say promote antisemitic and conspiracy tropes.', url: null },
  ]},
  { slug: 'james-fishback', name: 'James Fishback', subtitle: 'Rhetoric that invokes antisemitic conspiracy tropes', description: 'Commentator and writer who has been criticized for rhetoric that invokes antisemitic conspiracy tropes—including framing of "Zionist" or Jewish influence over media and institutions in ways that echo classic antisemitic narratives about secret control and dual loyalty.', image_url: '/agitators/jamesfishback.jpg', sources: [
    { date_label: 'Various', text: 'Statements and writing that critics say rely on antisemitic conspiracy framing.', url: null },
  ]},
]

// Conspiracy theories: individual myths with refutations, tags, categories, sources (HASHEM defined above)
const CONSPIRACIES = [
  { slug: 'khazar-myth', title: 'The Jews Of Today Aren\'t The Real Jews, They\'re Khazars!', summary: 'The "Khazar hypothesis" claims modern Jews descend from converts, not ancient Israelites. It is used to deny Jewish indigeneity and legitimacy.', body_text: '<h3>History</h3><p>The Khazar theory emerged in the 19th and early 20th centuries. It claimed that Ashkenazi Jews descended mainly from the Khazars, a Turkic people whose rulers supposedly converted to Judaism in the medieval period. The idea was later popularized in books and online to argue that modern Jews are "impostors" with no ancestral tie to the Land of Israel.</p><h3>Why</h3><p>Antisemites use the Khazar myth to deny Jewish indigeneity and legitimacy. If "today\'s Jews" are Khazar converts rather than Israelites, the argument goes, they have no historical claim to the land and Israel is a "colonial" fraud. The theory also fuels the idea that Jews are a "fake" or "invented" people.</p><h3>Facts</h3><p>Genetic and historical research has thoroughly debunked the Khazar-origin thesis. Ashkenazi Jews show substantial Levantine and Middle Eastern ancestry consistent with ancient Israelite and diaspora history. Jewish continuity in the land and across the diaspora is well documented. The Khazar kingdom did have a period of royal conversion, but there is no evidence that Ashkenazi Jewry descends mainly from Khazars. The theory is a pseudoscientific canard used to delegitimize Jews and Israel.</p>', category: 'Jewish identity & history', tags: ['Khazars', 'Jewish identity', 'antisemitic canard'], sort_order: 1, sources: [{ label: 'Hashem.Faith – Jewish identity', url: `${HASHEM}/` }] },
  { slug: 'jesus-boiling-hell', title: 'The Jews Hate Jesus And Believe He\'s Boiling In Excrement In Hell', summary: 'A vicious antisemitic libel that distorts Talmudic and Jewish tradition about Jesus and the afterlife.', body_text: '<h3>History</h3><p>Medieval Christian polemics and later antisemitic literature claimed that the Talmud describes Jesus suffering in hell, often in grotesque and scatological terms. These claims relied on mistranslations, out-of-context passages, or outright forgeries. The libel was used to justify violence and persecution of Jews for centuries.</p><h3>Why</h3><p>The myth is spread to portray Jews as hateful of Christianity and of Jesus, and to suggest that Jewish texts are inherently hostile or obscene. It is used to incite hatred and to justify discrimination or violence against Jews.</p><h3>Facts</h3><p>Jewish texts do not teach that Jesus (or any person) is "boiling in excrement" in hell. The Talmud is a vast legal and narrative corpus; isolated lines are often misattributed, mistranslated, or from debated passages. No mainstream Jewish tradition teaches the grotesque image antisemites attribute to it. The claim is a classic libel. Hashem.Faith addresses the Jesus narrative and Christianity in the Talmud with primary-source context.</p>', category: 'Jewish beliefs', tags: ['Jesus', 'Talmud', 'blood libel', 'Christian antisemitism'], sort_order: 2, sources: [{ label: 'Did the Jews kill Jesus?', url: `${HASHEM}/did-the-jews-kill-jesus/` }, { label: 'Christianity in the Talmud', url: `${HASHEM}/christianity-in-the-talmud/` }] },
  { slug: 'child-sacrifice-blood-libel', title: 'The Jews Believe In Child Sacrifice', summary: 'The blood libel: the false accusation that Jews use Christian (or other) children\'s blood in rituals.', body_text: '<h3>History</h3><p>The blood libel—the accusation that Jews murder non-Jewish children and use their blood in religious rituals—dates to the Middle Ages. It has appeared across Europe and elsewhere, often around Passover, and has repeatedly led to pogroms, trials, and murders. Despite papal and secular repudiations, the libel has been revived in antisemitic propaganda into the modern era.</p><h3>Why</h3><p>Antisemites use the blood libel to portray Jews as evil, ritualistic killers and to justify violence against them. It is a defining example of conspiracy thinking: a secret, murderous practice attributed to an entire group with no evidence.</p><h3>Facts</h3><p>The blood libel is completely false. No Jewish law or tradition permits or condones murder, child sacrifice, or the use of human blood in ritual. Jewish dietary law strictly forbids the consumption of blood. The accusation has been debunked by scholars, courts, and religious authorities countless times. It has caused immense suffering and remains a dangerous antisemitic myth.</p>', category: 'Jewish beliefs', tags: ['blood libel', 'child sacrifice', 'ritual murder'], sort_order: 3, sources: [{ label: 'Hashem.Faith', url: `${HASHEM}/` }] },
  { slug: 'non-jews-lesser', title: 'The Jews View Non-Jews As Lesser Beings', summary: 'The claim that Jewish texts or tradition teach that gentiles are inferior or subhuman.', body_text: '<h3>History</h3><p>Antisemites have long claimed that the Talmud or other Jewish texts teach that non-Jews (gentiles) are inferior, subhuman, or "animals." These claims rely on pulling isolated phrases out of context, mistranslating ancient legal or rhetorical passages, or citing forgeries. The same tropes have been used to justify discrimination and violence.</p><h3>Why</h3><p>The myth is used to portray Judaism as inherently hateful and to suggest that Jews view everyone else as lesser. It fuels the idea that Jews are a hostile, supremacist group and that "Jewish texts" justify mistreatment of non-Jews.</p><h3>Facts</h3><p>Jewish tradition does not teach that non-Jews are lesser or subhuman. The Talmud and later authorities recognize the dignity of all people; the Noahide laws apply to all humanity and assume moral responsibility for everyone. Antisemites quote-mine and mistranslate complex legal or aggadic passages to suggest otherwise. Hashem.Faith addresses these myths with primary-source context—including "Gentiles are human" and "Gentiles are not animals"—showing how the texts have been distorted.</p>', category: 'Jewish beliefs', tags: ['Talmud', 'gentiles', 'goyim', 'dehumanization'], sort_order: 4, sources: [{ label: 'Gentiles are human', url: `${HASHEM}/gentiles-are-human/` }, { label: 'Gentiles are not animals', url: `${HASHEM}/gentiles-are-not-animals/` }] },
  { slug: 'israel-genocide', title: 'Israel Is Committing a Genocide', summary: 'The charge that Israel\'s military actions in Gaza (or elsewhere) constitute genocide.', body_text: '<h3>History</h3><p>The charge that Israel is committing "genocide" against Palestinians has been leveled for decades and intensifies during armed conflicts. The term is often used in political rhetoric to condemn Israeli military actions, equate Israel with history\'s worst perpetrators, and isolate Israel internationally.</p><h3>Why</h3><p>Calling Israel\'s conduct genocide frames the conflict in the most morally absolute terms and denies any legitimacy to Israeli security concerns. It can also trivialize the legal and historical meaning of genocide and the Holocaust, and is sometimes used to deflect from the actions and goals of groups like Hamas.</p><h3>Facts</h3><p>Under international law (e.g., the Genocide Convention), genocide requires specific intent to destroy a national, ethnic, racial, or religious group in whole or in part. Israel is fighting Hamas and other armed groups that have attacked it; its stated aim is not to eliminate Palestinians as a people. Tragic civilian casualties and the horrors of war do not by themselves constitute genocide absent that intent. Conflating the Gaza conflict with genocide distorts the term and the Holocaust. See the site\'s Definition of genocide for more.</p>', category: 'Israel', tags: ['Israel', 'Gaza', 'genocide', 'IHRA'], sort_order: 5, sources: [{ label: 'Definition: Genocide', url: null }] },
  { slug: 'israel-discriminates-christians', title: 'Israel Discriminates Against Christians', summary: 'The claim that Israel systematically discriminates against or persecutes Christians.', body_text: '<h3>History</h3><p>Accusations that Israel discriminates against or persecutes Christians have appeared in some advocacy and media. They often surface in contexts where Israel is compared to its neighbors or where Christian holy sites and communities in the region are discussed.</p><h3>Why</h3><p>The claim is used to portray Israel as uniquely intolerant and to undermine support for Israel. It can be part of a broader narrative that singles out the Jewish state for criticism while downplaying the situation of religious minorities elsewhere in the region.</p><h3>Facts</h3><p>Christian communities in Israel have legal equality and freedom of worship. The Christian population in Israel has grown; Christian holy sites are protected by law and by longstanding arrangements. In contrast, Christians in many neighboring states face severe persecution, displacement, and violence. Israel is one of the few countries in the region where Christian communities have remained and grown. The claim that Israel systematically discriminates against Christians is not supported by the evidence and is often used to single out Israel unfairly.</p>', category: 'Israel', tags: ['Israel', 'Christians', 'religious freedom'], sort_order: 6, sources: [] },
  { slug: 'israel-bans-dna', title: 'Israel Bans DNA Tests', summary: 'The claim that Israel forbids or restricts DNA testing to hide Jewish ancestry or identity.', body_text: '<h3>History</h3><p>The claim that Israel "bans" or heavily restricts DNA tests has circulated online, often alongside Khazar or other ancestry conspiracy theories. It suggests that the state prevents people from learning their "real" ancestry to protect a narrative about Jewish identity.</p><h3>Why</h3><p>Antisemites and conspiracy theorists use the myth to suggest that Jewish identity or Israeli policy is built on a lie that would be exposed by genetic testing. It implies a cover-up and reinforces Khazar or other "fake Jew" narratives.</p><h3>Facts</h3><p>Israel does not ban DNA tests. Commercial and medical genetic testing is available in Israel as in many other countries. There are privacy and regulatory frameworks around genetic data, but no general prohibition. The myth is false and is often used to support the Khazar theory or other antisemitic canards about Jewish identity.</p>', category: 'Israel', tags: ['Israel', 'DNA', 'Khazars'], sort_order: 7, sources: [] },
  { slug: 'holocaust-denial', title: 'The Holocaust Didn\'t Happen or Was Exaggerated', summary: 'Holocaust denial or minimization: denying or downplaying the Nazi genocide of six million Jews.', body_text: '<h3>History</h3><p>Holocaust denial and minimization emerged among far-right and neo-Nazi circles after World War II. Deniers claim the genocide did not occur, that death tolls were exaggerated, or that gas chambers were not used. Despite overwhelming evidence, denial persists in some online and extremist communities and is illegal in many countries.</p><h3>Why</h3><p>Denial serves to rehabilitate Nazism, blame Jews for "lying" about history, and erase the specificity of antisemitic genocide. Minimization ("it wasn\'t that bad") has similar effects. Both are recognized as forms of antisemitism (e.g., IHRA definition).</p><h3>Facts</h3><p>The Holocaust—the systematic murder of approximately six million Jews by Nazi Germany and its collaborators—is one of the best-documented crimes in history. Evidence includes Nazi documentation, survivor testimony, physical sites (camps, mass graves), and decades of scholarship. Denial and minimization are antisemitic and false. See the site\'s Definition of Holocaust for more.</p>', category: 'Holocaust', tags: ['Holocaust', 'denial', 'Shoah'], sort_order: 8, sources: [{ label: 'Definition: Holocaust', url: null }] },
  { slug: 'israel-9-11', title: 'Israel Did 9/11 Or Knew In Advance', summary: 'The conspiracy that Israel or Jews orchestrated or had foreknowledge of the September 11 attacks.', body_text: '<h3>History</h3><p>Soon after the September 11, 2001, attacks, conspiracy theories emerged claiming that Israel, Israeli intelligence, or "the Jews" had orchestrated the attacks or had foreknowledge and allowed them to happen. Variations include claims that Jews were warned to stay away from the World Trade Center or that Israeli agents were seen celebrating. These claims have been repeatedly debunked but persist online.</p><h3>Why</h3><p>The conspiracy recycles classic antisemitic tropes: Jews as secretly powerful, malicious, or indifferent to the suffering of others. It deflects blame from the actual perpetrators and feeds into broader narratives of Jewish or Israeli control of events.</p><h3>Facts</h3><p>There is no evidence that Israel or Jews carried out or had advance knowledge of the 9/11 attacks. The 9/11 Commission Report and intelligence investigations attribute the attacks to al-Qaeda. Claims about Israeli foreknowledge or involvement have been investigated and rejected. The conspiracy is baseless and antisemitic.</p>', category: 'Power & control', tags: ['9/11', 'Israel', 'conspiracy'], sort_order: 9, sources: [] },
  { slug: 'jews-control-media', title: 'Jews Control the Media / Banks / Government', summary: 'The classic conspiracy that Jews secretly control major institutions.', body_text: '<h3>History</h3><p>The idea that Jews collectively control the media, banks, or government is a centuries-old antisemitic conspiracy. It appeared in European pamphlets and propaganda, in The Protocols of the Elders of Zion (a forgery), and in Nazi ideology. Today it surfaces in coded language about "globalists," "elites," or "the media" when the target is understood to be Jews.</p><h3>Why</h3><p>Antisemites use the trope to explain societal problems by blaming a hidden Jewish cabal. It provides a simple, malevolent explanation for complex events and justifies hostility or violence against Jews. It also reinforces the idea that Jews are not legitimate participants in society but secret rulers.</p><h3>Facts</h3><p>There is no basis in fact for the claim. Jews are a small minority worldwide with diverse views, occupations, and affiliations. No group "controls" the media, banks, or government in the way the conspiracy suggests. The trope has been used to justify persecution and genocide, including the Holocaust. It is a classic antisemitic conspiracy with no evidence.</p>', category: 'Power & control', tags: ['media', 'banks', 'government', 'control'], sort_order: 10, sources: [] },
  { slug: 'all-jews-wealthy', title: 'All Jews Are Wealthy', summary: 'The stereotype that all or most Jews are rich or financially privileged.', body_text: '<h3>History</h3><p>The "wealthy Jew" stereotype has deep roots in Christian Europe, where Jews were often restricted to moneylending and trade while being barred from landownership or guilds. When economic conditions worsened, Jews were blamed and scapegoated. The stereotype persisted through Nazi propaganda ("Jewish capitalism") and into modern conspiracy thinking.</p><h3>Why</h3><p>The myth is used to fuel envy, to blame Jews for economic inequality, and to suggest that Jewish success is illegitimate or exploitative. It often pairs with conspiracy theories about Jewish control of finance or media.</p><h3>Facts</h3><p>Jews, like any group, have a range of incomes and circumstances. Many Jews have lived and still live in poverty; Jewish communities include people of all economic backgrounds. The "all Jews are wealthy" idea is a stereotype with no basis in reality. It has been used to justify discrimination, violence, and genocide.</p>', category: 'Power & control', tags: ['stereotype', 'wealth', 'money'], sort_order: 11, sources: [] },
  { slug: 'israel-controls-america', title: 'Israel Controls America Or Has Unjust Influence In It', summary: 'The claim that Israel or "Zionists" dictate U.S. policy or have improper influence.', body_text: '<h3>History</h3><p>Accusations that Israel or "Zionists" control U.S. policy have circulated for decades. They often surface in debates over foreign aid, Middle East policy, or lobbying. The claim sometimes uses coded language about "Jewish power" or "dual loyalty" and overlaps with older antisemitic conspiracy tropes.</p><h3>Why</h3><p>The myth is used to explain U.S. support for Israel as the result of secret or illegitimate influence rather than as policy chosen by elected officials. It echoes dual-loyalty canards (that American Jews or officials put Israel ahead of America) and control tropes (that a hidden hand dictates policy).</p><h3>Facts</h3><p>The United States and Israel are allies with shared strategic and democratic interests; U.S. support for Israel is a matter of public policy, debate, and law. The claim that Israel "controls" America or that support is due to secret Jewish power is an antisemitic conspiracy with no evidence. It ignores the actual reasons for the alliance and falsely implies that support for Israel is illegitimate or coerced.</p>', category: 'Power & control', tags: ['Israel', 'America', 'dual loyalty', 'lobby'], sort_order: 12, sources: [] },
  { slug: 'aipac-foreign', title: 'AIPAC Is a Foreign Organization Compromising Our Politicians', summary: 'The claim that AIPAC is a foreign agent or improperly influences U.S. politics.', body_text: '<h3>History</h3><p>AIPAC (American Israel Public Affairs Committee) was founded in the 1950s as a U.S. advocacy organization focused on the U.S.–Israel relationship. For decades, critics have sometimes demanded that AIPAC or similar groups register under the Foreign Agents Registration Act (FARA), implying they are agents of a foreign government. The demand often overlaps with conspiracy narratives about "Jewish lobby" control.</p><h3>Why</h3><p>Framing AIPAC as a "foreign" or illegitimate influence suggests that American support for Israel is not a legitimate choice but the result of a foreign or ethnic lobby. It can echo antisemitic tropes about Jewish power and dual loyalty and deflect from the substantive policy debate.</p><h3>Facts</h3><p>AIPAC is a U.S. domestic advocacy organization. It does not represent the Israeli government and is not registered as a foreign agent under FARA. U.S. law distinguishes between domestic advocacy and representation of foreign principals. Demands that pro-Israel groups register under FARA often rely on a misapplication of the law and on antisemitic conspiracy framing. Hashem.Faith examines the legal and factual basis for these claims in depth.</p>', category: 'Power & control', tags: ['AIPAC', 'FARA', 'lobby', 'foreign agent'], sort_order: 13, sources: [{ label: 'Should AIPAC be registered under FARA?', url: `${HASHEM}/should-aipac-be-registered-under-fara/` }] },
]

// Talmud entries — myths about the Talmud refuted (sources: talmud.faithweb.com "The Real Truth About The Talmud" by Gil Student)
const TALMUD_BASE = 'http://talmud.faithweb.com/articles'
const TALMUD_ENTRIES = [
  { slug: 'real-truth-about-the-talmud', title: 'The Real Truth About The Talmud', summary: 'Why this resource exists: refuting false and malicious allegations about the Talmud.', body_text: '<h3>History</h3><p>Many lies circulate online about the Jewish Talmud, supported by "direct quotations" that are often wrong or taken out of context. Most people lack the scholarly background to verify these claims and have no way of knowing the accusations are false and intentionally misleading.</p><h3>Why</h3><p>Antisemites and polemicists have long weaponized fake or distorted Talmud quotes to portray Judaism as hostile to non-Jews. Showing the real truth requires demonstrating in detail how these accusations are wrong and intentionally misleading.</p><h3>Facts</h3><p>Judaism asserts that every human being is created in the image of the Lord and the primacy of integrity and honesty in all dealings. As Rabbi Malkiel Kotler, dean of the Lakewood Yeshiva, stated: "I strongly repudiate any assertions in the name of Judaism that do not represent and reflect this philosophy." Scholarly resources like talmud.faithweb.com provide context and refutation for each allegation.</p>', category: 'About The Talmud', tags: ['Talmud', 'misquotes', 'context'], sort_order: 1, sources: [{ label: 'The Real Truth About The Talmud', url: `${TALMUD_BASE}/intro.html` }] },
  { slug: 'what-is-the-talmud', title: 'What Is The Talmud?', summary: 'History and content of the Talmud: Mishnah, Gemara, Halakha, Aggadah.', body_text: '<h3>History</h3><p>The Talmud is the central text of Rabbinic Judaism. In Israel, the Mishna ("secondary") developed over roughly four centuries (200 B.C.–200 A.D.)—recordings of discussions of Biblical laws for application to Jewish life. The Babylonian Gemara ("completion"), in Aramaic, was added from about 200 to 500 A.D. The Mishna and Gemara together form the Talmud ("the Learning"), also known as Oral Law.</p><h3>Why</h3><p>Antisemites often treat the Talmud as a single sinister book. Understanding that it is a vast body of law, narrative, and debate—with disagreement and context—helps counter the myth that "the Talmud says" one simple thing.</p><h3>Facts</h3><p>The Talmud comprises six orders, numerous tractates, and mishnayot. Most of it is Halakha (legal discussion); the non-legal stories and sayings are Aggadah. It became regulatory for Jewish life until modern times and is still central for Orthodox Judaism. The Jews wiki and talmud.faithweb.com explain its structure and history in detail.</p>', category: 'About The Talmud', tags: ['Talmud', 'Mishnah', 'Gemara'], sort_order: 2, sources: [{ label: 'What Is The Talmud?', url: `${TALMUD_BASE}/whatis.html` }, { label: 'Judaism (references)', url: null }] },
  { slug: 'talmud-and-bible', title: 'Talmud and Bible', summary: 'Is the Talmud holier than the Bible?', body_text: '<h3>History</h3><p>Critics sometimes claim that Judaism elevates the Talmud above the Hebrew Bible (Tanakh). The claim is used to suggest that Jews follow a "second," secret, or hostile scripture.</p><h3>Why</h3><p>Framing the Talmud as "holier" or as replacing the Bible portrays Jewish tradition as deviant or hostile to the Written Torah. In fact, the Talmud is commentary and application of the same Scripture.</p><h3>Facts</h3><p>The Talmud is not holier than the Bible. It is the authoritative tradition of interpreting and applying the Written Torah—the same five books of Moses and the Prophets and Writings. Orthodox Judaism holds that the Oral Torah (expressed in the Talmud) was given alongside the Written Torah and transmitted through the sages. Both are integral to Jewish tradition; neither supersedes the other in the way the myth suggests.</p>', category: 'About The Talmud', tags: ['Talmud', 'Bible', 'Torah'], sort_order: 3, sources: [{ label: 'Talmud and Bible', url: `${TALMUD_BASE}/bible.html` }] },
  { slug: 'jewish-people-religion-or-race', title: 'Jewish People: Religion or Race?', summary: 'Where do gentiles fit in the Jewish worldview? Is Judaism a religion or a race?', body_text: '<h3>History</h3><p>Jews are an ethnoreligious group: identity is passed through family and community. The Torah and rabbis use the term "goy" in the ancient sense of a people or nation—a group with common history and destiny—not necessarily a territorial state. The question "religion or race?" has been weaponized by antisemites to racialize or delegitimize Jews.</p><h3>Why</h3><p>Antisemites sometimes claim that Jewish texts treat non-Jews as a separate, lesser "race." Understanding how Judaism views the Jewish people and other nations helps refute that distortion.</p><h3>Facts</h3><p>Judaism is a religion and Jews are a people (nation in the traditional sense). Gentile nations fit into the Jewish worldview: the Noahide laws apply to all humanity; righteous gentiles have a share in the world to come. Jewish tradition does not teach that gentiles are inferior or subhuman. The talmud.faithweb.com "Jewish People" and "Gentiles In Judaism" articles address this in detail.</p>', category: 'About The Talmud', tags: ['Judaism', 'gentiles', 'race'], sort_order: 4, sources: [{ label: 'Jewish People', url: `${TALMUD_BASE}/judaism.html` }, { label: 'Gentiles In Judaism', url: `${TALMUD_BASE}/gentiles.html` }, { label: 'What is a Jew?', url: 'http://en.wikipedia.org/wiki/Jew' }] },
  { slug: 'to-tell-the-truth', title: 'To Tell The Truth', summary: 'Are Jews commanded to lie about the Talmud?', body_text: '<h3>History</h3><p>One of the most persistent antisemitic canards is that Judaism or the Talmud commands Jews to lie to non-Jews about the contents of the Talmud—to hide its "true" evil from the outside world.</p><h3>Why</h3><p>The myth is used to dismiss any Jewish explanation of the Talmud as inherently dishonest and to justify seeking "secret" or "real" versions of Jewish teaching—often from antisemitic sources.</p><h3>Facts</h3><p>Jews are not commanded to lie about the Talmud. Jewish law and ethics require honesty in dealings with everyone. The Talmud is studied openly; there is no religious mandate to deceive about its contents. The allegation is false and malicious. Talmud.faithweb.com and Hashem.Faith both address this myth with citations.</p>', category: 'About The Talmud', tags: ['Talmud', 'lying', 'honesty'], sort_order: 5, sources: [{ label: 'To Tell The Truth', url: `${TALMUD_BASE}/lie.html` }] },
  { slug: 'gentiles-are-human', title: 'Gentiles Are Human', summary: 'The Talmud does not consider gentiles to be sub-human.', body_text: '<h3>History</h3><p>Antisemites have long claimed that the Talmud teaches that gentiles (non-Jews) are subhuman or "animals." These claims rely on pulling isolated phrases out of context, mistranslating legal or rhetorical passages, or citing forgeries.</p><h3>Why</h3><p>The myth is used to portray Judaism as inherently hateful and to suggest that Jews view everyone else as lesser—fueling the idea that Jews are a hostile, supremacist group.</p><h3>Facts</h3><p>Jewish tradition does not teach that gentiles are subhuman. The Talmud and later authorities recognize the dignity of all people. The Noahide laws apply to all humanity; the idea that every human is created in the image of G-d is foundational. Talmud.faithweb.com documents in detail how the "gentiles are not human" accusations are wrong and intentionally misleading.</p>', category: 'Alleged Racism In The Talmud', tags: ['gentiles', 'human', 'dignity'], sort_order: 6, sources: [{ label: 'Gentiles Are Human', url: `${TALMUD_BASE}/man.html` }, { label: 'Gentiles Are Human 2', url: `${TALMUD_BASE}/man2.html` }] },
  { slug: 'stealing-from-gentiles', title: 'Stealing From Gentiles', summary: 'The Talmud forbids stealing from gentiles.', body_text: '<h3>History</h3><p>Critics sometimes claim that the Talmud permits or encourages Jews to steal from non-Jews. The allegation is used to portray Jewish law as morally bankrupt and Jews as permitted to cheat others.</p><h3>Why</h3><p>The myth feeds the stereotype of the dishonest Jew and the idea that Jewish law applies only to dealings with other Jews.</p><h3>Facts</h3><p>The Talmud forbids stealing from gentiles. Theft is prohibited regardless of the victim; Jewish law does not permit cheating or stealing from anyone. Talmud.faithweb.com provides the textual context and refutation for this allegation.</p>', category: 'Alleged Racism In The Talmud', tags: ['theft', 'gentiles', 'ethics'], sort_order: 7, sources: [{ label: 'Stealing From Gentiles', url: `${TALMUD_BASE}/theft.html` }] },
  { slug: 'paying-gentile-wages', title: "Paying A Gentile's Wages", summary: 'The Talmud prohibits withholding a gentile\'s wages.', body_text: '<h3>History</h3><p>Another allegation is that Jewish law permits withholding payment or wages from non-Jewish workers.</p><h3>Why</h3><p>The claim is used to suggest that Jews are permitted to exploit or cheat gentiles in business.</p><h3>Facts</h3><p>The Talmud prohibits withholding a gentile\'s wages. Paying workers on time and treating them fairly applies to everyone. Talmud.faithweb.com addresses this accusation with sources.</p>', category: 'Alleged Racism In The Talmud', tags: ['wages', 'gentiles', 'ethics'], sort_order: 8, sources: [{ label: "Paying A Gentile's Wages", url: `${TALMUD_BASE}/wages.html` }] },
  { slug: 'tricking-gentiles', title: 'Tricking Gentiles', summary: 'The Talmud forbids lying to gentiles.', body_text: '<h3>History</h3><p>It is sometimes claimed that the Talmud permits or encourages Jews to deceive non-Jews in business or in general.</p><h3>Why</h3><p>The myth reinforces the canard that Jewish ethics allow dishonesty toward gentiles.</p><h3>Facts</h3><p>The Talmud forbids lying to gentiles. Honesty in all dealings is a core value; there is no exception for non-Jews. Talmud.faithweb.com refutes this allegation with citations.</p>', category: 'Alleged Racism In The Talmud', tags: ['lying', 'gentiles', 'ethics'], sort_order: 9, sources: [{ label: 'Tricking Gentiles', url: `${TALMUD_BASE}/cheat.html` }] },
  { slug: 'killing-gentiles', title: 'Killing Gentiles', summary: 'The Talmud prohibits killing gentiles.', body_text: '<h3>History</h3><p>Perhaps the most dangerous allegation is that the Talmud permits or commands Jews to kill non-Jews. This has been used for centuries to justify persecution and violence against Jews.</p><h3>Why</h3><p>The myth is used to portray Jews as murderous and Jewish law as sanctioning violence against gentiles—the opposite of the truth.</p><h3>Facts</h3><p>The Talmud prohibits killing gentiles. Murder is forbidden; every human is created in the image of G-d. The prohibition against murder applies to all people. Talmud.faithweb.com documents how the "permission to kill" accusations are false and taken out of context.</p>', category: 'Alleged Racism In The Talmud', tags: ['murder', 'gentiles', 'law'], sort_order: 10, sources: [{ label: 'Killing Gentiles', url: `${TALMUD_BASE}/kill.html` }] },
  { slug: 'various-accusations', title: 'Various Accusations', summary: 'Refuting a range of false accusations against the Talmud.', body_text: '<h3>History</h3><p>Many other accusations against the Talmud circulate online: that it is racist, immoral, or hostile to non-Jews in myriad specific ways. Often the same tactics appear—quotes out of context, mistranslation, or fabricated passages.</p><h3>Why</h3><p>Listing and refuting these systematically shows the pattern of distortion and helps readers recognize similar claims.</p><h3>Facts</h3><p>Talmud.faithweb.com has a "Various Accusations" page that refutes a range of these claims with scholarly context. The overall message is consistent: the Talmud, read in context, does not teach what antisemites claim.</p>', category: 'Alleged Racism In The Talmud', tags: ['Talmud', 'refutation'], sort_order: 11, sources: [{ label: 'Various Accusations', url: `${TALMUD_BASE}/short.html` }] },
  { slug: 'jesus-in-the-talmud', title: 'Jesus In The Talmud', summary: 'What, if anything, does the Talmud say about Jesus?', body_text: '<h3>History</h3><p>Medieval Christian polemics and later antisemitic literature claimed that the Talmud contains hostile or obscene references to Jesus. These claims relied on mistranslations, out-of-context passages, or forgeries. The libel was used to justify persecution of Jews for centuries.</p><h3>Why</h3><p>The myth is spread to portray Jews as hateful of Christianity and of Jesus, and to suggest that Jewish texts are inherently hostile—used to incite hatred and justify discrimination or violence.</p><h3>Facts</h3><p>What the Talmud actually says about Jesus (if the passages refer to the Christian figure at all) is limited and must be read in historical and textual context. It does not teach that Jesus is "boiling in excrement" or anything of the kind. Serious scholarship and sites like talmud.faithweb.com distinguish between the actual texts and the antisemitic libels built on them.</p>', category: 'Christianity In The Talmud', tags: ['Jesus', 'Christianity', 'Talmud'], sort_order: 12, sources: [{ label: 'Jesus In The Talmud', url: `${TALMUD_BASE}/jesus.html` }, { label: 'The Jesus Narrative', url: `${TALMUD_BASE}/jesusnarr.html` }] },
  { slug: 'blood-libel', title: 'Blood Libel', summary: 'Jews never eat blood; the blood libel is a deadly myth.', body_text: '<h3>History</h3><p>The blood libel—the accusation that Jews use Christian (or other) blood in ritual—has led to pogroms and murders for centuries. It is completely false. Jewish law strictly forbids consuming any blood; kosher slaughter and preparation are designed to remove blood.</p><h3>Why</h3><p>The libel is used to portray Jews as monstrous and ritual murder as part of Judaism—to justify violence against Jews.</p><h3>Facts</h3><p>Jews never eat blood. The Torah and Talmud prohibit it absolutely. The blood libel has no basis in Jewish teaching or practice. Talmud.faithweb.com addresses this in the "Blood Libel" article in the Jewish Holidays section.</p>', category: 'Jewish Holidays', tags: ['blood libel', 'Passover', 'kosher'], sort_order: 13, sources: [{ label: 'Blood Libel', url: `${TALMUD_BASE}/blood.html` }] },
  { slug: 'passover-haggadah', title: 'Passover', summary: 'The Passover Haggadah is not racist.', body_text: '<h3>History</h3><p>Critics have sometimes claimed that the Passover Seder or Haggadah contains racist or hostile references to non-Jews.</p><h3>Why</h3><p>The claim is used to portray a central Jewish ritual as hateful.</p><h3>Facts</h3><p>The Passover Haggadah tells the story of the Exodus and celebrates freedom. It is not racist; when it refers to enemies or oppressors, it is in the historical context of the narrative. Talmud.faithweb.com addresses this in the Passover article.</p>', category: 'Jewish Holidays', tags: ['Passover', 'Haggadah', 'Seder'], sort_order: 14, sources: [{ label: 'Passover', url: `${TALMUD_BASE}/passover.html` }] },
  { slug: 'kol-nidrei', title: 'Kol Nidrei', summary: 'Does Kol Nidrei give Jews permission to deceive?', body_text: '<h3>History</h3><p>Kol Nidrei is a declaration recited at the start of Yom Kippur (Day of Atonement). Antisemites have claimed it annuls all oaths and gives Jews permission to break promises or lie to non-Jews.</p><h3>Why</h3><p>The myth is used to suggest that Jewish worship includes a ritualized permission to be dishonest—again, to portray Jews as untrustworthy.</p><h3>Facts</h3><p>Kol Nidrei has a specific legal and liturgical meaning: it addresses certain types of vows made between the individual and G-d, under narrow conditions. It does not annul obligations to other people or permit lying or breaking promises. Talmud.faithweb.com explains the real meaning in "Kol Nidrei: Permission to deceive?"</p>', category: 'Jewish Holidays', tags: ['Kol Nidrei', 'Yom Kippur', 'vows'], sort_order: 15, sources: [{ label: 'Kol Nidrei', url: `${TALMUD_BASE}/kolnidre.html` }] },
  { slug: 'sex-three-year-old', title: 'The Talmud Does Not Permit Sex With A Three Year Old', summary: 'Refuting the horrific allegation that the Talmud permits sexual abuse of children.', body_text: '<h3>History</h3><p>One of the most grotesque allegations against the Talmud is that it permits sexual relations with a three-year-old. This claim is based on a complete misreading of ancient legal and textual context.</p><h3>Why</h3><p>The allegation is spread to portray Jewish tradition as morally depraved and to shock and disgust readers—a form of antisemitic libel.</p><h3>Facts</h3><p>The Talmud does not permit sex with a three-year-old or any child. The passages in question deal with legal definitions (e.g., betrothal) in a specific historical context and do not authorize or condone abuse. Talmud.faithweb.com has an article titled "The Talmud Does Not Permit Sex With A Three Year Old" that explains the textual and legal context. Sexual morality in the Talmud is strict.</p>', category: 'Immorality In The Talmud', tags: ['sexual morality', 'children', 'Talmud'], sort_order: 16, sources: [{ label: 'The Talmud Does Not Permit Sex With A Three Year Old', url: `${TALMUD_BASE}/three.html` }] },
  { slug: 'rabbi-eleazar-prostitutes', title: 'Rabbi Eleazar and the Prostitutes', summary: 'The full story behind a distorted anecdote.', body_text: '<h3>History</h3><p>Antisemites sometimes cite a Talmudic story about Rabbi Eleazar and prostitutes to suggest that the Talmud is obscene or that rabbis condone immorality.</p><h3>Why</h3><p>The story is taken out of context to portray Jewish sages as immoral.</p><h3>Facts</h3><p>When read in full, the story teaches the opposite: it is about repentance, humility, and the dignity of every person. Talmud.faithweb.com provides "Rabbi Eleazar and the Prostitutes: The Full Story" with context.</p>', category: 'Immorality In The Talmud', tags: ['Aggadah', 'ethics', 'repentance'], sort_order: 17, sources: [{ label: 'Rabbi Eleazar and the Prostitutes', url: `${TALMUD_BASE}/eleazar.html` }] },
  { slug: 'in-the-image-of-god', title: '"In The Image Of G-d"', summary: 'Gentiles are created in the image of G-d.', body_text: '<h3>History</h3><p>Jewish tradition holds that every human being is created in the image of G-d (Genesis 1:27). This includes all people, not only Jews.</p><h3>Why</h3><p>Antisemites claim that the Talmud restricts this idea to Jews or denies it for gentiles. Refuting that is central to showing the real Jewish view.</p><h3>Facts</h3><p>Gentiles are created in the image of G-d. The Talmud and later authorities affirm the dignity of every human. Talmud.faithweb.com has an article "In The Image Of G-d" that documents this.</p>', category: 'Miscellaneous', tags: ['image of G-d', 'gentiles', 'dignity'], sort_order: 18, sources: [{ label: '"In The Image Of G-d"', url: `${TALMUD_BASE}/image.html` }] },
  { slug: 'goy', title: '"Goy"', summary: 'Is "goy" a derogatory term used by Jews about gentiles?', body_text: '<h3>History</h3><p>The Hebrew word "goy" (plural "goyim") means "nation" or "people." In the Torah, Israel is itself called a "goy." It is the standard term for a non-Jewish nation or person in Jewish texts.</p><h3>Why</h3><p>Antisemites and some critics claim that "goy" is a slur or derogatory term, implying that Jews view non-Jews with contempt.</p><h3>Facts</h3><p>"Goy" is not inherently derogatory. It is the traditional Hebrew term for a nation; the Torah uses it for the Jewish people as well. Context matters: it can be used neutrally or, in casual speech, with negative connotations—just as "gentile" or "non-Jew" can. Talmud.faithweb.com addresses this in the "Goy" article. As the Jews wiki notes, the Torah and rabbis used "goy" in the ancient sense of a group with common history and destiny.</p>', category: 'Miscellaneous', tags: ['goy', 'language', 'gentiles'], sort_order: 19, sources: [{ label: '"Goy"', url: `${TALMUD_BASE}/goy.html` }] },
  { slug: 'ethics-of-the-fathers', title: 'Ethics Of The Fathers', summary: 'The section of the Mishnah dedicated to ethical sayings of the sages.', body_text: '<h3>History</h3><p>Pirkei Avot ("Ethics of the Fathers") is a tractate of the Mishnah devoted to ethical maxims and sayings of the rabbinic sages. It is widely studied and quoted.</p><h3>Why</h3><p>Showing the Talmud\'s ethical content counters the myth that the Talmud is only hostile or legalistic.</p><h3>Facts</h3><p>Ethics of the Fathers emphasizes character, humility, justice, and learning. It reflects the same philosophy that every human is created in the image of G-d and that integrity and honesty are paramount. Talmud.faithweb.com has an article on it; it is recommended reading for anyone wanting a sample of Talmudic ethics.</p>', category: 'Miscellaneous', tags: ['Pirkei Avot', 'ethics', 'Mishnah'], sort_order: 20, sources: [{ label: 'Ethics Of The Fathers', url: `${TALMUD_BASE}/avot.html` }] },
  { slug: 'schindlers-list', title: "Schindler's List", summary: 'The source of a disputed quotation.', body_text: '<h3>History</h3><p>A quotation sometimes attributed to the Talmud has been circulated in connection with "Schindler\'s List" or Holocaust memory—often in a distorted or false form.</p><h3>Why</h3><p>Misattributed or fake Talmud quotes are used to smear Jewish tradition or to suggest that the Talmud teaches something it does not.</p><h3>Facts</h3><p>Talmud.faithweb.com has an article documenting the source of the disputed quotation and clarifying what the Talmud actually says. When in doubt, check primary sources and scholarly refutations.</p>', category: 'Miscellaneous', tags: ['Schindler\'s List', 'quotation', 'Talmud'], sort_order: 21, sources: [{ label: "Schindler's List", url: `${TALMUD_BASE}/schindler.html` }] },
  { slug: 'recommended-reading', title: 'Recommended Reading', summary: 'Books and links for understanding the Talmud.', body_text: '<h3>History</h3><p>Serious understanding of the Talmud requires access to reliable translations, commentaries, and introductory works. Gil Student\'s site recommends resources for further study.</p><h3>Why</h3><p>Directing readers to sound resources helps them avoid antisemitic or polemical "Talmud exposés" that rely on fake or out-of-context quotes.</p><h3>Facts</h3><p>Talmud.faithweb.com includes a "Recommended Reading" page and a link to "The Complete Idiot\'s Guide to Understanding the Talmud" (Rav Parry). The site also links to related articles and to "A Modern Blood Libel" by Rabbi Dr. Immanuel Jakobovits (refuting Israel Shahak\'s distortions).</p>', category: 'Miscellaneous', tags: ['resources', 'Talmud'], sort_order: 22, sources: [{ label: 'Recommended Reading', url: `${TALMUD_BASE}/read.html` }, { label: 'Related Links', url: `${TALMUD_BASE}/links.html` }, { label: 'The Complete Idiot\'s Guide to Understanding the Talmud', url: 'http://www.ravparry.com/' }] },
]

// Misconceptions (hub) and topic content
const MISCONCEPTIONS = [
  { slug: 'israel', title: 'Israel', summary: 'Myths about Israel\'s founding, "colonialism," and the conflict.' },
  { slug: 'talmud', title: 'The Talmud', summary: 'Misquotes and false claims about what the Talmud says.' },
  { slug: 'jewish-race', title: 'The Jewish "Race"', summary: 'Facts about Jewish identity: ethnicity, religion, and race.' },
  { slug: 'conspiracy', title: 'Conspiracy Theories', summary: 'Classic antisemitic conspiracy myths and why they\'re false.' },
]

// Topic body_text enriched with context that Hashem.Faith articles address
const MISCONCEPTION_TOPICS = [
  { topic_slug: 'israel', title: 'Israel', body_text: '<p><strong>"Israel is a colonial project."</strong> Jews have had a continuous presence in the land for millennia. Modern Zionism sought self-determination in the ancestral homeland after persecution in Europe and elsewhere. The state was established with international recognition (UN 1947–48). Calling it "colonial" erases Jewish indigeneity and history.</p><p><strong>"Israel has no right to exist."</strong> Israel is a sovereign state and a member of the UN. Denying only the Jewish state\'s right to exist, while accepting others, is a form of antisemitism (see IHRA definition).</p><p><strong>"Israel is committing genocide."</strong> As covered in Definitions, genocide requires intent to destroy a group. Israel is fighting Hamas; its aim is not to eliminate Palestinians as a people. Casualties of war are not by themselves genocide.</p><p>The name "Israel" and its biblical and historical meaning are explained in depth at Hashem.Faith.</p>', sort_order: 1 },
  { topic_slug: 'talmud', title: 'The Talmud', body_text: '<p><strong>"The Talmud says X about non-Jews."</strong> The Talmud is a vast legal and narrative corpus. Isolated lines are often taken out of context, mistranslated, or from passages that are debated or obsolete. Serious understanding requires scholarship and context.</p><p><strong>"The Talmud is secret or evil."</strong> The Talmud is studied openly and is the basis of Jewish law and tradition. Antisemites have long weaponized fake or distorted "quotes" to portray Jews as hostile to non-Jews.</p><p>Hashem.Faith addresses myths that the Talmud commands lying, dehumanizes gentiles, or is hostile to Christianity—with citations and context.</p>', sort_order: 2 },
  { topic_slug: 'jewish-race', title: 'The Jewish "Race"', body_text: '<p><strong>"Are Jews a race?"</strong> Jews are an ethnoreligious group. Identity is passed through family and community; there is genetic diversity but also shared ancestry among many Jews. Nazis racialized Jews to justify genocide; today, many Jews identify as both an ethnicity and a religion.</p><p><strong>"Jews are white / not white."</strong> Jewish identity predates modern racial categories. Jews have been classified differently in different times and places. Reducing Jews to a single "race" ignores this history and diversity.</p><p>Hashem.Faith discusses whether Judaism is a religion or race, where gentiles fit in the Jewish worldview, and refutes the myth that Jewish texts dehumanize non-Jews.</p>', sort_order: 3 },
  { topic_slug: 'conspiracy', title: 'Conspiracy Theories', body_text: '<p><strong>"Jews control the media / banks / government."</strong> Classic antisemitic conspiracy with no evidence. It has been used for centuries to blame Jews for societal problems and to justify violence.</p><p><strong>"The Holocaust didn\'t happen" or "was exaggerated."</strong> Holocaust denial is false and antisemitic. The evidence—documentation, testimony, sites—is overwhelming.</p><p><strong>"Israel did 9/11" or "Jews knew in advance."</strong> Baseless conspiracy theories that recycle antisemitic tropes about Jewish power and malice.</p><p>The claim that "the Jews killed Jesus" and conspiracy narratives about Jewish lobbying (e.g. AIPAC/FARA) are addressed with historical and legal context at Hashem.Faith.</p>', sort_order: 4 },
]

async function run() {
  const conn = await mysql.createConnection(config)
  console.log('Connected to MySQL.')

  await conn.execute('SET FOREIGN_KEY_CHECKS = 0')
  await conn.execute('TRUNCATE TABLE talmud_sources')
  await conn.execute('TRUNCATE TABLE conspiracy_sources')
  await conn.execute('TRUNCATE TABLE agitator_sources')
  await conn.execute('TRUNCATE TABLE misconception_topics')
  await conn.execute('TRUNCATE TABLE talmud_entries')
  await conn.execute('TRUNCATE TABLE conspiracies')
  await conn.execute('TRUNCATE TABLE agitators')
  await conn.execute('TRUNCATE TABLE misconceptions')
  await conn.execute('TRUNCATE TABLE definitions')
  await conn.execute('TRUNCATE TABLE timeline_events')
  await conn.execute('SET FOREIGN_KEY_CHECKS = 1')
  console.log('Cleared existing data.')

  // Timeline events
  console.log('Inserting timeline_events...')
  for (const e of TIMELINE_EVENTS) {
    await conn.execute(
      'INSERT INTO timeline_events (year, label, region, description, source_label, source_url) VALUES (?, ?, ?, ?, ?, ?)',
      [e.year, e.label, e.region || null, e.description || null, e.source_label || null, e.source_url || null]
    )
  }
  console.log(`  ${TIMELINE_EVENTS.length} events.`)

  // Definitions (with Hashem.Faith further_reading)
  console.log('Inserting definitions...')
  for (const d of DEFINITIONS) {
    const furtherReading = DEFINITION_FURTHER_READING[d.slug] || []
    await conn.execute(
      'INSERT INTO definitions (slug, title, summary, body_text, further_reading) VALUES (?, ?, ?, ?, ?)',
      [d.slug, d.title, d.summary, d.body_text || null, furtherReading.length ? JSON.stringify(furtherReading) : null]
    )
  }
  console.log(`  ${DEFINITIONS.length} definitions.`)

  // Agitators + sources
  console.log('Inserting agitators and agitator_sources...')
  for (const a of AGITATORS) {
    const [r] = await conn.execute(
      'INSERT INTO agitators (slug, name, subtitle, description, image_url) VALUES (?, ?, ?, ?, ?)',
      [a.slug, a.name, a.subtitle, a.description, a.image_url || null]
    )
    const agitatorId = r.insertId
    let order = 0
    for (const s of a.sources) {
      await conn.execute(
        'INSERT INTO agitator_sources (agitator_id, date_label, text, url, sort_order) VALUES (?, ?, ?, ?, ?)',
        [agitatorId, s.date_label, s.text, s.url || null, order++]
      )
    }
  }
  console.log(`  ${AGITATORS.length} agitators with sources.`)

  // Conspiracies + sources
  console.log('Inserting conspiracies and conspiracy_sources...')
  for (const c of CONSPIRACIES) {
    const [r] = await conn.execute(
      'INSERT INTO conspiracies (slug, title, summary, body_text, category, tags, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?)',
      [c.slug, c.title, c.summary || null, c.body_text || null, c.category || null, c.tags ? JSON.stringify(c.tags) : null, c.sort_order ?? 0]
    )
    const conspiracyId = r.insertId
    let order = 0
    for (const s of c.sources || []) {
      await conn.execute(
        'INSERT INTO conspiracy_sources (conspiracy_id, label, url, sort_order) VALUES (?, ?, ?, ?)',
        [conspiracyId, s.label, s.url || null, order++]
      )
    }
  }
  console.log(`  ${CONSPIRACIES.length} conspiracies with sources.`)

  // Talmud entries + sources (talmud.faithweb.com)
  console.log('Inserting talmud_entries and talmud_sources...')
  for (const t of TALMUD_ENTRIES) {
    const [r] = await conn.execute(
      'INSERT INTO talmud_entries (slug, title, summary, body_text, category, tags, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?)',
      [t.slug, t.title, t.summary || null, t.body_text || null, t.category || null, t.tags ? JSON.stringify(t.tags) : null, t.sort_order ?? 0]
    )
    const entryId = r.insertId
    let order = 0
    for (const s of t.sources || []) {
      await conn.execute(
        'INSERT INTO talmud_sources (talmud_entry_id, label, url, sort_order) VALUES (?, ?, ?, ?)',
        [entryId, s.label, s.url || null, order++]
      )
    }
  }
  console.log(`  ${TALMUD_ENTRIES.length} talmud entries with sources.`)

  // Misconceptions + topics (one topic per misconception, matched by slug)
  console.log('Inserting misconceptions and misconception_topics...')
  const topicBySlug = Object.fromEntries(MISCONCEPTION_TOPICS.map((t) => [t.topic_slug, t]))
  for (const m of MISCONCEPTIONS) {
    const [r] = await conn.execute(
      'INSERT INTO misconceptions (slug, title, summary) VALUES (?, ?, ?)',
      [m.slug, m.title, m.summary]
    )
    const misId = r.insertId
    const t = topicBySlug[m.slug]
    if (t) {
      const furtherReading = MISCONCEPTION_FURTHER_READING[t.topic_slug] || []
      await conn.execute(
        'INSERT INTO misconception_topics (misconception_id, topic_slug, title, body_text, further_reading, sort_order) VALUES (?, ?, ?, ?, ?, ?)',
        [misId, t.topic_slug, t.title, t.body_text, furtherReading.length ? JSON.stringify(furtherReading) : null, t.sort_order]
      )
    }
  }
  console.log(`  ${MISCONCEPTIONS.length} misconceptions with topics.`)

  await conn.end()
  console.log('Seed done.')
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
